# NumPy Exercises

#### Import NumPy as np

In [1]:
import numpy as np 

#### Create an array of 10 zeros

In [5]:
arrray_zeros=np.zeros(10)
arrray_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
array_ones=np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
array_five=np.full(10,fill_value=5)
array_five

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [ ]:
array_integers=np.arange(10,51)
array_integers

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [12]:
array_even=np.arange(10,50,2)
array_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
array_reshape=np.arange(0,9).reshape(3,3)
array_reshape

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
array_identity=np.identity(3)
array_identity


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [22]:
array_rand=np.random.rand(10)
array_rand

array([0.36006898, 0.07970303, 0.40813074, 0.42221765, 0.33234442,
       0.75405218, 0.10232804, 0.23152596, 0.35787392, 0.82054501])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [26]:
array_random=np.random.normal(size=25)
array_random

array([ 0.48218906,  1.54677489, -0.51606836, -0.51203588, -1.32175717,
        0.41376822,  0.71403276,  2.16213553, -0.09526736,  0.58507582,
        0.11662035, -0.56979717, -0.5696133 , -2.05945165,  0.69036115,
        1.60061236,  0.83990788, -0.37641617,  0.46182969, -0.34941191,
        1.22308341, -0.79856609, -0.6461677 ,  0.06160389, -1.57275207])

#### Create the following matrix:

In [28]:
array_follwing=np.linspace(0,1)
array_follwing

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
array_linearly=np.linspace(0,1,20)
array_linearly

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Numpy Indexing and Selection, write code that reproduces the output of the cell below

In [63]:
array=np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
array[2:,2:]# or solution array[2:][2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [65]:
array[-2,-1] # or solution array[-1][0]

20

In [66]:
array[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
array[-1:,:] # or solution array[-1:][:]

array([[21, 22, 23, 24, 25]])

In [69]:
array[-2:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [73]:
array.sum()

325

#### Get the standard deviation of the values in mat

In [75]:
np.std(array)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
array.sum(axis=0) # axis=0 in numpy indicates columns
# axis =1 in pandas indicates columns 

array([55, 60, 65, 70, 75])

==========

In [ ]:
#self study Task 2
# https://www.w3schools.com/quiztest/quiztest.asp?qtest=NUMPY
#https://www.w3schools.com/python/numpy/numpy_exercises.asp
#https://www.w3resource.com/python-exercises/numpy/index.pup

# Great Job!